/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/alumnos/': RouteRecordInfo<'/alumnos/', '/alumnos', Record<never, never>, Record<never, never>>,
    '/alumnos/[name]': RouteRecordInfo<'/alumnos/[name]', '/alumnos/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/docentes/': RouteRecordInfo<'/docentes/', '/docentes', Record<never, never>, Record<never, never>>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/materias/': RouteRecordInfo<'/materias/', '/materias', Record<never, never>, Record<never, never>>,
    '/pipi': RouteRecordInfo<'/pipi', '/pipi', Record<never, never>, Record<never, never>>,
  }
}
